### ISSUE TITLE
Endless reverse recyclerview?

### ISSUE THREAD

**Issue by kenyee** [henrytao-me/recyclerview-multistate-section-endless-adapter#7]
Can you use this to do a reverse recyclerview?
Use case is a chat conversation where you start at the bottom but might want to scroll backwards to see previous chat history but only the latest messages are loaded initially

**Comment by henrytao-me** [comment]
Hi @kenyee,
It's pretty good idea. Let me make some examples for it and ping you when it's ready. It's roughly about a week.

**Comment by henrytao-me** [comment]
Hi @kenyee 

I just found out that you can use LayoutManager to have reverse recyclerview. 

```
LinearLayoutManager layoutManager = new LinearLayoutManager(getActivity());
layoutManager.setReverseLayout(true);
```
